version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client
    ports: 
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8000
    
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild


volumes:
  anime:
